### PR TITLE
WC-503 - Local Docker Improvements - es

### PR DESCRIPTION
**Pull request by pamprn09**
Added elastic search altis module

### CODE REVIEW

**Comment by alwaysblank** [comment]
@pamprn09 Could you tell me how you tested this locally? I'm not sure how to get local-vip up and running on its own.

**Comment by pamprn09** [comment]
> @pamprn09 Could you tell me how you tested this locally? I'm not sure how to get local-vip up and running on its own.

Try running `composer update humanmade/local-vip` on `rmm/wp-core-local-docker`

**Comment by alwaysblank** [comment]
> Try running composer update humanmade/local-vip on rmm/wp-core-local-docker

This didn't work for me because the branch that `rmm/wp-core-local-docker` is using for `humanmade/local-vip` is `composer-2`, so `composer update humanmade/local-vip` only updates to the head of that branch. 

I ended up just applying these changes manually, but I'd like to be able to test that ES is running, indexing, and being used on searches. Can you tell me how you tested that?

**Review by alwaysblank — CHANGES_REQUESTED** [review]
These changes are motivated by the needs of `rmm/wp-core-local-docker`, but as-is this PR won't be compatible. That repo uses the `composer-2` branch of `human-made/local-vip` to support Composer 2: https://github.com/rmm/wp-core-local-docker/blob/9da86fe3ec228947d68ec8d6a82b3783c22c2b54/composer.json#L22-L24

This branch appears to have been branched off `main`, so it's using the Composer 1 plugin api, and will throw the following error if uses in the `wp-core-local-vip` `composer.json`: 

```shell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires humanmade/local-vip dev-feat/WC-503/add-elastic-search-module -> satisfiable by humanmade/local-vip[dev-feat/WC-503/add-elastic-search-module].
    - humanmade/local-vip dev-feat/WC-503/add-elastic-search-module requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
```

This branch should be updated to be compatible with the `composer-2` branch.

**Comment by pamprn09** [comment]
> These changes are motivated by the needs of `rmm/wp-core-local-docker`, but as-is this PR won't be compatible. That repo uses the `composer-2` branch of `human-made/local-vip` to support Composer 2: https://github.com/rmm/wp-core-local-docker/blob/9da86fe3ec228947d68ec8d6a82b3783c22c2b54/composer.json#L22-L24
> 
> This branch appears to have been branched off `main`, so it's using the Composer 1 plugin api, and will throw the following error if uses in the `wp-core-local-vip` `composer.json`:
> 
> ```shell
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires humanmade/local-vip dev-feat/WC-503/add-elastic-search-module -> satisfiable by humanmade/local-vip[dev-feat/WC-503/add-elastic-search-module].
>     - humanmade/local-vip dev-feat/WC-503/add-elastic-search-module requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
> ```
> 
> This branch should be updated to be compatible with the `composer-2` branch.

Ben, sorry I'm mistaken. This changed supposed to be at `wp-core-local-vip`. I'm closing this PR and adding in the existing one.

**Pull request closed without merging**
