### PR TITLE
Allow PHP 8.0 and (conditionally) replace Memcached with Redis

### PR DESCRIPTION
**Pull request by alwaysblank**
A (now-reverted) change to `composer-2` added support for PHP 8.0, but I neglected to realize that the image used for PHP 8 removes memcached support in favor of Redis, causing actual uses of this package to break. This PR resolves that issue by replacing memcached with Redis if a non-supporting image is selected. Although this takes it would of parity with VIP (which uses Memcached in it's production infrastructure) it does allow the local dev environment to run on PHP 8.

### CODE REVIEW

**Review by smccafferty — APPROVED** [review]

**Comment by hsiemon-globant** [comment]
Hi @alwaysblank, I'm having an issue with the database in a fresh install. The database don't pass the health check using mysql (more than 5 minutes waiting), if I change to mariadb the database starts but won't allow connections from other containers.

image

**Comment by alwaysblank** [comment]
@hsiemon-globant I'm not able to replicate this issue on my local environment with a test install. Can you provide the exact steps you used to create your test environment? What operating system are you using? Are there any existing containers with these names?

I'd also be curious if the container is reporting any errors internally. What do the logs for the db container look like?

Additionally, you might be able to get some information by logging into the db container CLI and manually running the healthcheck command: https://github.com/humanmade/local-vip/blob/76521fa2aad9d86063a20a41cfad615c454cd5de/inc/composer/class-docker-compose-generator.php#L272-L286

**Comment by hsiemon-globant** [comment]
@alwaysblank Sorry Ben, I forgot to delete the db-data volume so mysql was trying to use a mariadb volume and was throwing an error. But now I'm having an issue with the domain, did you guys removed the option to use custom domains? I was using something like vip.test and now I'm forced to use vip.local

**Comment by alwaysblank** [comment]
@hsiemon-globant You should still be able to set a custom domain, although the key has changed. I've updated the README: https://github.com/humanmade/local-vip/tree/19-allow-php-8.0#getting-started

**Comment by hsiemon-globant** [comment]
Thanks @alwaysblank 🙏

Is it possible to switch from mysql to mariadb?

**Comment by alwaysblank** [comment]
> Is it possible to switch from mysql to mariadb?

It's probably possible, but it's not something that's on my radar. It doesn't look like we're using a specialized docker image for the DB container, so you could probably just change the image it points at: https://github.com/humanmade/local-vip/blob/1a146918049319c06f69425821035b8973ff1b6a/inc/composer/class-docker-compose-generator.php#L224-L258

**Review by kadamwhite — APPROVED** [review]

**Pull request merged**
