### PR TITLE
v2.0: Composer 2 and M1 support

### PR DESCRIPTION
**Pull request by kadamwhite**
This branch contains a number of changes to make `local-vip` work better with ARM processors (Apple Silicon chips, for example), and to better support Composer 2. This branch is in active use on multiple projects, and the reason it has not been merged is that doing so might cause issues for a few specific teams currently using the `main` branch.

I've opened this PR as a statement of intent, that we deploy the `composer-2` changes @smccafferty has introduced in late 
August. We will alert the relevant teams that this upgrade is coming, to give them a month to either pin their dependency on the current `main` version (1.3.3), or update to support this new `composer-2` version.

**Update**: Given the breaking changes, **this will be released as version 2.0.0**. To support teams which may need more time to upgrade to the upcoming version, the current `main` release has been [packaged as Release v1.3.3](https://github.com/humanmade/local-vip/releases/tag/v1.3.3), which is also available via [Packagist](https://packagist.org/packages/humanmade/local-vip#1.3.3).

### CODE REVIEW

**Comment by alwaysblank** [comment]
Once merged, this should resolve #15.

**Comment by kadamwhite** [comment]
@alwaysblank we discussed merging this and tagging the 2.0 version at the end of August, but it fell off my radar. Do you think we're ready to land this branch back into `main` and tag the new release?

**Comment by alwaysblank** [comment]
@kadamwhite I actually misspoke in the standup: This PR _doesn't_ include PHP 8 support, that's #22. If we want to include PHP 8 support, we may want to merge that PR into this one (and potentially consider bumping the docker image support it has to support 8.1 beta: https://github.com/humanmade/docker-wordpress-php/issues/119)

Apart from that, this PR should be good to merge. I've been using it for a while. The primary change I added (support mkcert) seems to work like a charm. Haven't tested on M1, though; I only have intel.

**Comment by smccafferty** [comment]
@kadamwhite we would need to confirm that this wouldn't impact relevant clients, as I believe they were the ones using an earlier version.

**Pull request merged**
