### PR TITLE
WC-503 - Local Docker Improvements

### PR DESCRIPTION
**Pull request by pamprn09**
1. Integrate phpmyadmin
2. Localhost documentation
3. Get image for nnn
4. Update PHP version
5. Fix debug file

### CODE REVIEW

**Comment by alwaysblank** [comment]
@pamprn09 What's the reason for adding phpmyadmin? Are the [`composer server db`](https://github.com/humanmade/local-vip/tree/main/docs#available-commands) commands not working?

**Comment by pamprn09** [comment]
> @pamprn09 What's the reason for adding phpmyadmin? Are the [`composer server db`](https://github.com/humanmade/local-vip/tree/main/docs#available-commands) commands not working?
It was  something asked in the ticket: that phpMyAdmin was added. Should [`composer server db`] also add phpMyAdmin? Not know for sure.

**Comment by alwaysblank** [comment]
@pamprn09 I'd be reluctant to add functionality that essentially duplicates existing functionality (in the form of the `composer server db` commands) based on a client request on a separate project, given that this is a package we maintain internally vs. a client project. Could you get some clarification on why the existing solution doesn't work?

**Comment by pamprn09** [comment]
Sure, I can do that. Just enlighten me, please: does composer server db
creates a phpmyadmin interface? Or it shows tables in the terminal?

Em sex., 19 de nov. de 2021 às 15:47, Ben ***@***.***>
escreveu:

**Comment by alwaysblank** [comment]
There are [several commands](https://github.com/humanmade/local-vip/tree/main/docs#available-commands):

- `composer server db` - Logs into MySQL on the DB container.
- `composer server db info` - Print MySQL connection details.
- `composer server db sequel` - Opens a connection to the database in Sequel Pro.

This is in addition to using the [WP-CLI database commands](https://developer.wordpress.org/cli/commands/db/), i.e.
`composer server cli -- db export backup.sql`.

None of these generate a phpMyAdmin interface, but the original ticket says `phpmyadmin needs to be a part of this, as there is no way to look at db now in local`. These commands provide many different ways to "look at [the] db". Sequel Pro, for instance, is a free application for MacOS that allows a direct interface to the database in the manner of phpMyAdmin (and is much more pleasant to use, IMO). `composer server db info` provides information that can be used to connect to the database with whatever application the user would like to use, and `composer server db` allows them to log into the MySQL console and run queries directly.

**Comment by pamprn09** [comment]
> There are [several commands](https://github.com/humanmade/local-vip/tree/main/docs#available-commands):
> 
> * `composer server db` - Logs into MySQL on the DB container.
> * `composer server db info` - Print MySQL connection details.
> * `composer server db sequel` - Opens a connection to the database in Sequel Pro.
> 
> This is in addition to using the [WP-CLI database commands](https://developer.wordpress.org/cli/commands/db/), i.e. `composer server cli -- db export backup.sql`.
> 
> None of these generate a phpMyAdmin interface, but the original ticket says `phpmyadmin needs to be a part of this, as there is no way to look at db now in local`. These commands provide many different ways to "look at [the] db". Sequel Pro, for instance, is a free application for MacOS that allows a direct interface to the database in the manner of phpMyAdmin (and is much more pleasant to use, IMO). `composer server db info` provides information that can be used to connect to the database with whatever application the user would like to use, and `composer server db` allows them to log into the MySQL console and run queries directly.

I agree with you. I just added a simple subtitle pointing those existing commands at the [READ.me file](https://github.com/rmm/wp-core-local-docker/pull/10/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R60), this is an existing PR.
I'm closing this PR.

**Pull request closed without merging**
